- name: Installing packages
  yum: name={{ item }}
  with_items:
      - pacemaker
      #- resource-agents
      - pcs
      #- fence-agents-all
      #- fence-agents-virsh 

#todo keep selinux(?) and firewall online
- name: disable selinux
  selinux: policy=targeted state=disabled

- name: ensure firewalld is disabled and stopped
  service: name=firewalld enabled=no state=stopped

- name: ensure corosync and pacemaker is disabled and stopped
  service: name=corosync enabled=no state=stopped
  
- name: ensure pacemaker is disabled and stopped
  service: name=pacemaker enabled=no state=stopped

- name: add clusterware user
  user: name=hacluster password=$6$r2IvlBZP$.CjWNPmJpAAs1fThIlZ999o6jxaz1HBkxuQLiT27qD4p8BasLa.UIQlaH5YzssTRhNT4GnKIfu9OBbjgEJ5gR/

- name: ensure pcsd enabled and started
  service: name=pcsd enabled=yes state=started

# todo add cluster list from hosts(?)
#- name: Authenticate to the cluster
#  command: pcs cluster auth -u hacluster {{ omc_cluster_hosts }}
