- name: Installing packages
  yum: name={{ item }}
  with_items:
      - vim
      - wget
      - iftop
      - atop
      - hdparm
      - lshw

- name: copy hosts file
  copy: src="hosts" dest="/etc/hosts"
