# file: roles/install-postgresql-on-el6/vars/main.yml -- here are the variables that you don't want to change unnecessarily.

postgresql_repo_OEL:
  - { version: "{{ postgresql_version }}", repo: "http://yum.postgresql.org/{{ postgresql_version }}/redhat/rhel-{{ el_version }}-x86_64/pgdg-oraclelinux95-{{ postgresql_version }}-1.noarch.rpm" }
 
postgresql_repo_RedHat:
  - { version: "{{ postgresql_version }}", repo: "http://yum.postgresql.org/{{ postgresql_version }}/redhat/rhel-{{ el_version }}-x86_64/pgdg-redhat94-{{ postgresql_version }}-1.noarch.rpm" }
 
postgresql_repo_Scientific:
  - { version: "{{ postgresql_version }}", repo: "http://yum.postgresql.org/{{ postgresql_version }}/redhat/rhel-{{ el_version }}-x86_64/pgdg-sl94-{{ postgresql_version }}-1.noarch.rpm" }
 
postgresql_repo_CentOS:
  - { version: "{{ postgresql_version }}", repo: "http://yum.postgresql.org/{{ postgresql_version }}/redhat/rhel-{{ el_version }}-x86_64/pgdg-centos94-{{ postgresql_version }}-1.noarch.rpm" }
 