- name: Installing prereqs
  yum: name={{ item }}
  with_items:
      - git
      - make 
      - rpm-build 
      - python2-devel 
      - python-setuptools

- name: git clone mamonsu 
  git: repo=https://github.com/postgrespro/mamonsu
       dest=/tmp/mamonsu

- name: make rpm from source
  shell: make rpm 
  args:
    chdir: /tmp/mamonsu

- name: install mamonsu from local file
  shell: yum localinstall -y mamonsu*.rpm
  args:
    chdir: /tmp/mamonsu
